instance {ε α : Type} [DecidableEq ε] [DecidableEq α] : DecidableEq (Except ε α)
  | Except.error e1, Except.error e2 =>
    match decEq e1 e2 with
    | isTrue h => isTrue (by rw [h])
    | isFalse h => isFalse (by intro eq; injection eq; contradiction)
  | Except.ok a1, Except.ok a2 =>
    match decEq a1 a2 with
    | isTrue h => isTrue (by rw [h])
    | isFalse h => isFalse (by intro eq; injection eq; contradiction)
  | Except.error _, Except.ok _ => isFalse (by intro eq; contradiction)
  | Except.ok _, Except.error _ => isFalse (by intro eq; contradiction)

def snoc {α : Type} (list : List α) (element : α) : List α :=
  match list with
  | [] => [element]
  | head :: tail => head :: (snoc tail element)
#guard snoc [] 1 = [1]
#guard snoc [1] 2 = [1,2]
#guard snoc [5,4] 3 = [5,4,3]
#guard snoc [5,4,2,1] 3 = [5,4,2,1,3]

def snoc_len_gt_0 : ∀ (l: List α) (x: α), (snoc l x).length > 0
| [] => by intros; rw [snoc]; simp
| hd :: tl => by intros; rw [snoc]; simp

-- Generated by ChatGPT

theorem List.map_comp {α β γ : Type} (f : β → γ) (g : α → β) (l : List α) :
  (l.map (f ∘ g)) = (l.map g).map f := by grind
theorem tail_reduces_length{α: Type} (l : List α) : 0 < l.length → l.tail!.length < l.length := by
  intro h
  dsimp [List.tail!]
  cases l <;> grind

theorem List.sum_pairwise (l₁ l₂: List α) (p: α → Nat)(len_eq: l₁.length = l₂.length)(pf: ∀ (i: Fin l₁.length), p l₁[i] < p l₂[i]): (l₁.map p).sum < (l₂.map p).sum := by
  by_cases h: l₁.length = 0
  · sorry
  · by_cases h₂: l₁.length = 1
    · rw [List.map.eq_def,List.map.eq_def]
      cases l₁
      · grind
      · simp
        rename_i hd tl
        cases tl <;> sorry
    · rw [List.map.eq_def,List.map.eq_def]
      cases l₁
      · grind
      · simp
        rename_i hd tl
        cases l₂
        · grind
        · rename_i hd₂ tl₂
          have asdf: 0 < (hd::tl).length := by grind
          have asdfdf := List.sum_pairwise tl tl₂ p (by grind)
          have i_zero: Fin ((hd :: tl).length) := {val:= 0, isLt:= by grind}
          have ok := pf i_zero
          sorry

partial def List.zip_many {α : Type} [Inhabited α ] (rows: List (List α)): List (List α):= match H: rows with
| [] => []
| (hd :: tl) =>
  let rows := hd :: tl
  if rows_empty??: rows.any List.isEmpty then
    []
  else
    let heads := rows.map List.head!
    let tails := rows.map List.tail!
    have rows_tails_len_eq: rows.length = tails.length := by grind
    have k : ∀ (i : Fin tails.length), tails[i].length < rows[i].length := by
        intro i
        simp at rows_empty??
        have y : rows[i].length >0 := by cases _: rows[i] <;> grind
        have hhh :=tail_reduces_length rows[i] y
        grind
    --have obv : (tails.map (·.length)).sum < (rows.map (·.length)).sum := by

    -- have t : (map ((fun x => x.length) ∘ tail!) rows).sum < (map (fun x => x.length) rows).sum := by
    --    rw [List.map_comp]
    --    apply obv
    heads :: List.zip_many tails
termination_by (rows.map (·.length)).sum

#guard
  [[1,2,3],[4,5,6],[7,8,9]].zip_many
    = [[1,4,7],[2,5,8],[3,6,9]]

#guard
  [[1,2],[3,4],[5,6]].zip_many
    = [[1,3,5],[2,4,6]]

#guard
  [[1,2],[3],[4,5,6]].zip_many
    = [[1,3,4]]

#guard
  ([] : List (List Nat)).zip_many = []
